"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AppShell, Header } from "./order-management";

type View = "All Orders" | "Action Required" | "Stalled" | "Push Failed" | "On Hold" | "SLA At Risk" | "Cancellation Pending" | "Partial Fulfilment";
type Order = { id: string; client: string; type: string; state: string; wms: string; shipment: string; sla: string; warehouse: string; exception: string; owner: string; updated: string; tags: View[]; integration: string; country: string; courier: string; source: string; created: string; despatch: string };

const views: Array<[View, number]> = [["All Orders", 1248], ["Action Required", 18], ["Stalled", 6], ["Push Failed", 3], ["On Hold", 11], ["SLA At Risk", 7], ["Cancellation Pending", 2], ["Partial Fulfilment", 5]];
const records: Order[] = [
  { id: "BW-10482", client: "Aster & Ash", type: "B2C", state: "Ready", wms: "Sent", shipment: "Awaiting scan", sla: "Within SLA", warehouse: "London", exception: "—", owner: "—", updated: "2m ago", tags: ["All Orders"], integration: "Healthy", country: "GB", courier: "DPD UK", source: "Shopify", created: "Today, 10:14", despatch: "Today, 17:00" },
  { id: "BW-10481", client: "Canyon Club", type: "B2B", state: "In Fulfilment", wms: "Pick started", shipment: "Not created", sla: "At risk", warehouse: "Rotterdam", exception: "SLA at risk", owner: "Ops", updated: "4m ago", tags: ["All Orders", "SLA At Risk", "Action Required"], integration: "Healthy", country: "NL", courier: "DHL", source: "ERP", created: "Today, 10:02", despatch: "Today, 14:00" },
  { id: "BW-10480", client: "Aster & Ash", type: "B2C", state: "Validating", wms: "Not sent", shipment: "Not created", sla: "Breached", warehouse: "—", exception: "Address invalid", owner: "Client", updated: "12m ago", tags: ["All Orders", "Action Required"], integration: "Blocked", country: "GB", courier: "—", source: "Shopify", created: "Today, 09:42", despatch: "Today, 13:00" },
  { id: "BW-10479", client: "Kanso Studio", type: "B2C", state: "In Transit", wms: "Despatched", shipment: "In transit", sla: "Within SLA", warehouse: "Sydney", exception: "—", owner: "—", updated: "14m ago", tags: ["All Orders"], integration: "Healthy", country: "AU", courier: "AusPost", source: "WooCommerce", created: "Today, 09:36", despatch: "Today, 12:00" },
  { id: "BW-10478", client: "Canyon Club", type: "Subscription", state: "On Hold", wms: "Acknowledged", shipment: "Awaiting scan", sla: "Paused", warehouse: "Los Angeles", exception: "Missing SKU", owner: "Client", updated: "18m ago", tags: ["All Orders", "On Hold", "Action Required"], integration: "Healthy", country: "US", courier: "UPS", source: "API", created: "Today, 09:31", despatch: "Tomorrow, 12:00" },
  { id: "BW-10477", client: "Aster & Ash", type: "B2C", state: "Partially fulfilled", wms: "Despatched", shipment: "Awaiting scan", sla: "At risk", warehouse: "London", exception: "Quantity mismatch", owner: "Warehouse", updated: "22m ago", tags: ["All Orders", "Partial Fulfilment", "Action Required", "SLA At Risk"], integration: "Healthy", country: "GB", courier: "DPD UK", source: "Shopify", created: "Today, 09:22", despatch: "Today, 12:00" },
  { id: "BW-10471", client: "Canyon Club", type: "B2B", state: "Ready", wms: "Push failed", shipment: "Not created", sla: "At risk", warehouse: "Los Angeles", exception: "WMS push failed", owner: "Tech / Ops", updated: "28m ago", tags: ["All Orders", "Push Failed", "Action Required", "SLA At Risk"], integration: "Failed", country: "US", courier: "FedEx", source: "ERP", created: "Today, 09:03", despatch: "Today, 11:00" },
  { id: "BW-10463", client: "Kanso Studio", type: "B2C", state: "Cancellation Pending", wms: "Awaiting cancellation", shipment: "Awaiting scan", sla: "At risk", warehouse: "Rotterdam", exception: "Awaiting confirmation", owner: "Warehouse", updated: "41m ago", tags: ["All Orders", "Cancellation Pending", "Action Required"], integration: "Healthy", country: "DE", courier: "DHL", source: "Shopify", created: "Today, 08:42", despatch: "Today, 10:30" },
  { id: "BW-10458", client: "Aster & Ash", type: "B2C", state: "In Fulfilment", wms: "Acknowledged", shipment: "Not created", sla: "Within SLA", warehouse: "London", exception: "No WMS event", owner: "Tech / Ops", updated: "1h ago", tags: ["All Orders", "Stalled"], integration: "Stale", country: "GB", courier: "DPD UK", source: "Shopify", created: "Today, 08:14", despatch: "Today, 15:00" },
];

const badge = (value: string) => <span className={`pill ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>;
const optionalFields = ["Integration State", "Country", "Courier", "Source", "Created", "Required Despatch"] as const;
type OptionalField = typeof optionalFields[number];

export function OrdersWorkbench() {
  const [view, setView] = useState<View>("All Orders");
  const [search, setSearch] = useState("");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [columnsOpen, setColumnsOpen] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [visibleOptional, setVisibleOptional] = useState<OptionalField[]>([]);
  const clientScoped = false; // The header's default All Clients view is internal; a client view omits this column.
  const filtered = useMemo(() => records.filter((record) => (view === "All Orders" || record.tags.includes(view)) && Object.values(record).join(" ").toLowerCase().includes(search.toLowerCase())), [view, search]);
  const toggleColumn = (field: OptionalField) => setVisibleOptional((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]);
  return <AppShell><Header title="Order Management" copy="Monitor, investigate and manage orders across your fulfilment network." />
    <section className="workbench-summary"><SummaryCard label="Orders Today" value="1,248" detail="Across 4 warehouses" /><SummaryCard label="Action Required" value="18" detail="6 high priority" warn /><SummaryCard label="SLA At Risk" value="7" detail="2 within 1 hour" warn /><SummaryCard label="Fulfilment SLA" value="96.8%" detail="Target 95%" /></section>
    <section className="panel canonical-pipeline"><div className="panel-head"><div><h2>Order pipeline</h2><p>Canonical Bundle lifecycle with operational signals surfaced in context.</p></div></div><div className="canonical-stages">{[["Validating", "12 orders", "3 require attention"], ["Ready", "89 orders", "1 routing review"], ["In Fulfilment", "184 orders", "2 push failures · 7 SLA at risk"], ["Fulfilled", "71 orders", "4 awaiting first scan"], ["In Transit", "243 orders", "2 carrier exceptions"], ["Delivered", "96 orders", "All within SLA"]].map(([stage,count,signal], index) => <div className="canonical-stage" key={stage}><span>{stage}</span><b>{count}</b><small className={signal.includes("require") || signal.includes("failure") || signal.includes("risk") ? "signal-warning" : ""}>{signal}</small>{index < 5 && <i>→</i>}</div>)}</div></section>
    <section className="orders-workbench dense-workbench"><div className="panel-head"><div><h2>Orders</h2><p>Saved views filter this same operational table.</p></div><div className="create-wrap"><button className="primary" onClick={() => setCreateOpen((current) => !current)}>+ Create Order <span>⌄</span></button>{createOpen && <div className="create-menu"><button>Manual Order</button><button>Bulk Upload Orders</button></div>}</div></div>
      <div className="queue-tabs" role="tablist">{views.map(([name,count]) => <button role="tab" aria-selected={view === name} className={view === name ? "active" : ""} onClick={() => setView(name)}>{name}<b>{count}</b></button>)}</div>
      <div className="table-controls"><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order, customer, reference or warehouse" /></label><button className="filter" onClick={() => setFiltersOpen((current) => !current)}>Filters <span>2</span></button><button className="filter" onClick={() => setColumnsOpen((current) => !current)}>Columns</button><button className="filter">Export</button></div>
      {filtersOpen && <div className="filter-drawer"><b>Active filters</b><span>Client: All clients</span><span>Warehouse: All warehouses</span><span>SLA: At risk or breached</span><button onClick={() => setFiltersOpen(false)}>Done</button></div>}
      {columnsOpen && <div className="columns-drawer"><b>Optional columns</b>{optionalFields.map((field) => <label key={field}><input type="checkbox" checked={visibleOptional.includes(field)} onChange={() => toggleColumn(field)} /> {field}</label>)}<button onClick={() => setColumnsOpen(false)}>Done</button></div>}
      <DenseTable rows={filtered} showClient={!clientScoped} optional={visibleOptional} />
    </section>
  </AppShell>;
}

function SummaryCard({ label, value, detail, warn = false }: { label: string; value: string; detail: string; warn?: boolean }) { return <article><span>{label}</span><b>{value}</b><small className={warn ? "red-text" : ""}>{detail}</small></article> }

function DenseTable({ rows, showClient, optional }: { rows: Order[]; showClient: boolean; optional: OptionalField[] }) { const value = (order: Order, field: OptionalField) => ({ "Integration State": order.integration, Country: order.country, Courier: order.courier, Source: order.source, Created: order.created, "Required Despatch": order.despatch })[field]; return <div className="orders-table-wrap dense-table"><div className="table-meta">{rows.length} matching orders <span>•</span> Updated just now</div><table className="orders-table"><thead><tr><th>Order</th>{showClient && <th>Client</th>}<th>Order Type</th><th>Order State</th><th>WMS State</th><th>Shipment State</th><th>SLA</th><th>Warehouse</th><th>Exception</th><th>Owner</th><th>Updated</th>{optional.map((field) => <th key={field}>{field}</th>)}</tr></thead><tbody>{rows.map((order) => <tr key={order.id} className="order-row"><td><Link href={`/orders/${order.id}`}><b>#{order.id}</b></Link></td>{showClient && <td>{order.client}</td>}<td>{order.type}</td><td>{badge(order.state)}</td><td>{order.wms}</td><td>{order.shipment}</td><td>{badge(order.sla)}</td><td>{order.warehouse}</td><td>{order.exception === "—" ? <span className="quiet">—</span> : <Link className="order-issue" href={`/orders/${order.id}`}>{order.exception}</Link>}</td><td>{order.owner}</td><td>{order.updated}</td>{optional.map((field) => <td key={field}>{value(order, field)}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state">No orders match the selected saved view and search.</div>}</div> }
