"use client";

import { useState } from "react";

const tabs = ["Overview", "Items & Fulfilment", "Shipments", "Documents", "Activity", "Queries", "Integrations"] as const;
type Tab = typeof tabs[number];
const badge = (value: string) => <span className={`pill ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>;

export function OrderDetailTabs({ activeTab, onTabChange }: { activeTab: string; onTabChange: (tab: string) => void }) {
  return <><nav className="detail-tabs" aria-label="Order detail sections">{tabs.map((tab) => <button key={tab} className={activeTab === tab ? "active" : ""} onClick={() => onTabChange(tab)}>{tab}{tab === "Queries" && <b className="tab-badge">1</b>}</button>)}</nav><OrderTabContent tab={activeTab as Tab} /></>;
}

function OrderTabContent({ tab }: { tab: Tab }) {
  if (tab === "Overview") return <OverviewTab />;
  if (tab === "Items & Fulfilment") return <ItemsTab />;
  if (tab === "Shipments") return <DetailLayout><section className="panel detail-panel"><h2>Shipments</h2><div className="shipment-card"><div className="shipment-icon">↗</div><div><span>Shipment reference · SHP-UK-884201</span><b>DPD UK · Next Day</b><p>Latest scan: Awaiting first carrier scan</p></div>{badge("Awaiting First Scan")}</div><div className="info-grid">{[["Courier", "DPD UK"], ["Service", "Next Day"], ["Shipment reference", "SHP-UK-884201"], ["Tracking", "1550 8442 0191"], ["Weight", "0.8 kg"], ["Parcel count", "1"], ["Shipment state", "Awaiting First Scan"], ["Latest scan", "Not provided by carrier yet"]].map(([label,value]) => <Info label={label} value={value} key={label} />)}</div></section></DetailLayout>;
  if (tab === "Documents") return <DetailLayout><section className="panel detail-panel"><h2>Documents</h2><p>Documents stay attached to the order and are explicit when unavailable.</p>{[["Shipping label", "Created by London Fulfilment", "PDF"], ["Commercial invoice", "Not provided by this warehouse", "Unavailable"], ["Customs documents", "Not required for this domestic shipment", "Not required"], ["Packing slip", "Created by London Fulfilment", "PDF"]].map(([name,copy,status]) => <button className="document-row" title={`Opens ${name} when available.`} key={name}><span>▤</span><div><b>{name}</b><small>{copy}</small></div>{badge(status)}<i>→</i></button>)}</section></DetailLayout>;
  if (tab === "Activity") return <ActivityTimeline />;
  if (tab === "Queries") return <QueriesTab />;
  return <IntegrationJourney />;
}

function ItemsTab() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const items = [{ name: "Balance Daily Serum", sku: "AA-SER-30", ordered: "2", allocated: "2", shipped: "1", batch: "B-240821", expiry: "31 Aug 2027", location: "LON-A-14-02" }, { name: "Renewal Night Cream", sku: "AA-NCR-50", ordered: "1", allocated: "1", shipped: "1", batch: null, expiry: null, location: null }];
  return <DetailLayout><section className="panel detail-panel"><h2>Items & Fulfilment</h2><p>Expand a SKU to inspect the warehouse-level fulfilment data available to Bundle.</p>{items.map((item) => <div className="sku-block" key={item.sku}><button className="fulfilment-row sku-toggle" onClick={() => setExpanded(expanded === item.sku ? null : item.sku)} aria-expanded={expanded === item.sku}><div className="product-image">{item.name[0]}</div><div className="product-copy"><b>{item.name}</b><small>SKU · {item.sku}</small></div><div><small>ORDERED</small><b>{item.ordered}</b></div><div><small>ALLOCATED</small><b>{item.allocated}</b></div><div><small>SHIPPED</small><b className={item.shipped !== item.ordered ? "amber-text" : ""}>{item.shipped}</b></div><i>{expanded === item.sku ? "⌃" : "⌄"}</i></button>{expanded === item.sku && <div className="warehouse-detail"><h3>Warehouse detail</h3><div className="info-grid"><Info label="Available" value={item.name === "Balance Daily Serum" ? "41" : "Not provided by this warehouse"} /><Info label="Allocated" value={item.allocated} /><Info label="Picked" value={item.shipped} /><Info label="Packed" value={item.shipped} /><Info label="Shipped" value={item.shipped} /><Info label="Batch / lot number" value={item.batch ?? "Not provided by this warehouse"} /><Info label="Expiry date" value={item.expiry ?? "Not provided by this warehouse"} /><Info label="Inventory location" value={item.location ?? "Not provided by this warehouse"} /></div></div>}</div>)}</section></DetailLayout>;
}

function OverviewTab() { return <DetailLayout context={false}><section className="panel detail-panel"><div className="panel-head"><div><h2>Overview</h2><p>Order information is synchronised from its source of truth.</p></div></div><section className="source-of-truth"><div><small>Source</small><b>Shopify</b><span>Last synced 3 minutes ago</span></div><button title="Opens this order in Shopify.">Open in Shopify ↗</button></section><div className="source-message"><b>Changes to this order should be made in Shopify before warehouse acknowledgement.</b><p>Bundle will re-sync and revalidate eligible changes automatically.</p></div><div className="info-grid">{[["Order identifiers", "EU33691 · External ref #SP-36193"], ["Source channel", "Shopify"], ["Order type", "B2C"], ["Customer", "Amelia Wren · amelia@showpo.com"], ["Delivery address", "21 Cloudesley Road, London N1 0HS, United Kingdom"], ["Warehouse", "London Fulfilment"], ["Routing reason", "Available stock + UK Next Day service"], ["Courier / service", "DPD UK · Next Day"], ["Order value", "£148.00"], ["Required dispatch", "21 Aug 2026, 17:00 BST"]].map(([label,value]) => <Info label={label} value={value} key={label} />)}</div></section><aside className="context-stack"><section className="panel override-context"><h3>Operational overrides</h3><p>Internal Wayfindr users may apply authorised overrides only where the order state, lock point and permission allow it.</p><ul><li>Every override is audited with old/new values and actor.</li><li>Bundle validates downstream propagation.</li><li>A failed propagation creates an exception.</li></ul><button className="outline wide" title="Shows permitted internal overrides for this order state.">View permitted overrides</button></section><section className="panel source-rules"><h3>Source editability</h3><div><b>Storefront / API orders</b><span>Edit in source before acknowledgement.</span></div><div><b>Manual / bulk orders</b><span>Editability depends on creator, state and lock point.</span></div></section></aside></DetailLayout> }

type ActivityFilter = "All" | "Order" | "Warehouse" | "Shipment" | "User Actions" | "Integration" | "Exceptions";
const activityEvents: Array<{ time: string; title: string; actor: string; type: ActivityFilter; detail: string; change?: [string, string, string] }> = [
  { time: "12:18:04", title: "Partial fulfilment detected", actor: "Bundle · System", type: "Exceptions", detail: "Shipment reconciliation found 1 unit outstanding." },
  { time: "12:14:32", title: "Shipment despatched", actor: "Scale3PL · Mintsoft", type: "Shipment", detail: "Parcel created. Tracking awaiting first carrier scan." },
  { time: "10:02:11", title: "WMS acknowledged order", actor: "Scale3PL · API", type: "Warehouse", detail: "Warehouse reference: SC-354592" },
  { time: "09:51:24", title: "Delivery address changed", actor: "Harry Emerson · Wayfindr", type: "User Actions", detail: "Order amendment validated and forwarded to the warehouse.", change: ["Postcode", "BH12 2JQ", "BH12 3AB"] },
  { time: "09:43:03", title: "Inventory allocated", actor: "Bundle · Inventory", type: "Order", detail: "3 units reserved." },
  { time: "09:42:58", title: "Order validation passed", actor: "Bundle", type: "Order", detail: "Schema, address and SKU checks completed successfully." },
  { time: "09:42:41", title: "Order received", actor: "Shopify", type: "Integration", detail: "Source order SP-36193 ingested into Bundle." },
];

function ActivityTimeline() {
  const [filter, setFilter] = useState<ActivityFilter>("All");
  const events = activityEvents.filter((event) => filter === "All" || event.type === filter);
  return <DetailLayout><section className="panel detail-panel activity-panel"><div className="panel-head"><div><h2>Activity</h2><p>Immutable chronological audit trail. Every operational change has an actor, timestamp and source.</p></div><span className="audit-lock">Immutable</span></div><div className="activity-filters" role="tablist">{(["All", "Order", "Warehouse", "Shipment", "User Actions", "Integration", "Exceptions"] as ActivityFilter[]).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="activity-timeline">{events.map((event) => <article className={`activity-event ${event.type.toLowerCase().replaceAll(" ", "-")}`} key={`${event.time}-${event.title}`}><time>{event.time}</time><i/><div><b>{event.title}</b><span>{event.actor}</span><p>{event.detail}</p>{event.change && <div className="change-record"><small>{event.change[0]}</small><b>{event.change[1]} <em>→</em> {event.change[2]}</b></div>}</div></article>)}</div>{events.length === 0 && <div className="empty-state">No activity matches this filter.</div>}</section></DetailLayout>;
}

function QueriesTab() {
  const [formOpen, setFormOpen] = useState(false);
  const [type, setType] = useState("Stock / fulfilment query");
  const [priority, setPriority] = useState("Normal");
  const [message, setMessage] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const submit = () => { if (message.trim()) { setSubmitted(true); setFormOpen(false); setMessage(""); } };
  return <DetailLayout><section className="panel detail-panel queries-panel"><div className="panel-head"><div><h2>Queries <span className="query-count">1</span></h2><p>Client and Wayfindr teams can resolve operational issues without leaving the order.</p></div><button className="primary" onClick={() => setFormOpen((current) => !current)}>+ Raise Query</button></div>{formOpen && <div className="query-form"><label>Query type<select value={type} onChange={(event) => setType(event.target.value)}>{["Order amendment", "Cancellation request", "Delivery query", "Tracking issue", "Stock / fulfilment query", "Returns query", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Message<textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Describe the operational issue or requested change." /></label><div className="query-form-row"><label>Optional attachment<input type="file" /></label><label>Priority<select value={priority} onChange={(event) => setPriority(event.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label></div><div><button className="outline" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary" onClick={submit}>Submit query</button></div></div>}<QueryThread id="QUERY-001" type="Stock / fulfilment query" status="Open" owner="Warehouse Ops" createdBy="Amelia Wren · Client" created="Today, 12:24 BST" messages={[["Amelia Wren", "Client", "Can you confirm when the outstanding serum will ship?", "12:24"], ["Jess Lin", "Wayfindr", "I have asked London Fulfilment to confirm the residual dispatch plan.", "12:36"]]} />{submitted && <QueryThread id="QUERY-002" type={type} status="Awaiting Wayfindr" owner="Wayfindr" createdBy="Eliza Morgan · Wayfindr" created="Just now" messages={[["Eliza Morgan", "Wayfindr", "New query submitted and attached to this order.", "Just now"]]} />}</section></DetailLayout>;
}

const integrationEvents = [
  ["10:01:42", "Shopify → Bundle", "Order received", "Success", "shopify:SP-36193"],
  ["10:01:46", "Bundle", "Bundle ingestion", "Success", "ing:EU33691:01"],
  ["10:01:49", "Bundle", "Validation", "Success", "val:EU33691:02"],
  ["10:01:54", "Bundle → Inventory", "Inventory allocation", "Success", "inv:LDN:8842"],
  ["10:01:58", "Bundle → Scale3PL", "Order push", "Success", "push:EU33691:03"],
  ["10:02:11", "Scale3PL → Bundle", "Order acknowledgement", "Success", "Warehouse ref SC-354592"],
  ["12:14:32", "Scale3PL → Bundle", "Warehouse event: despatched", "Success", "wms:SC-354592:despatch"],
  ["12:14:35", "Bundle", "Shipment creation", "Success", "ship:SHP-UK-884201"],
  ["—", "DPD UK → Bundle", "Carrier events", "Waiting", "Awaiting first carrier scan"],
];

function IntegrationJourney() {
  const [technicalOpen, setTechnicalOpen] = useState(false);
  return <DetailLayout><section className="panel detail-panel integration-journey"><div className="panel-head"><div><h2>Integrations</h2><p>Order-specific journey from Shopify to carrier events.</p></div><span className="internal-label">Internal view</span></div><div className="journey-flow">{["Shopify", "Bundle ingestion", "Validation", "Inventory allocation", "WMS push", "WMS acknowledgement", "Warehouse events", "Shipment creation", "Carrier events"].map((item, index) => <span key={item}>{item}{index < 8 && <i>↓</i>}</span>)}</div><div className="integration-table"><div className="integration-heading"><span>Timestamp</span><span>Source</span><span>Event</span><span>Result</span><span>Reference / correlation ID</span></div>{integrationEvents.map(([time,source,event,result,reference]) => <div className="integration-event" key={`${time}-${event}`}><span>{time}</span><b>{source}</b><div>{event}</div>{badge(result)}<code>{reference}</code></div>)}</div><div className="integration-failure-note"><b>Failures and actions</b><span>When an event fails, Bundle links it directly to the related exception and its recommended action in Action Required.</span></div><button className="technical-toggle integration-technical" onClick={() => setTechnicalOpen((current) => !current)}>Technical detail {technicalOpen ? "⌃" : "⌄"}</button>{technicalOpen && <code className="technical-response">Sanitised metadata · correlation_id=push:EU33691:03 · request_schema=v2/order/create · response_status=202 · warehouse_reference=SC-354592</code>}</section></DetailLayout>;
}

function QueryThread({ id, type, status, owner, createdBy, created, messages }: { id: string; type: string; status: string; owner: string; createdBy: string; created: string; messages: string[][] }) { return <article className="query-thread"><div className="query-thread-head"><div><span>{id}</span><b>{type}</b></div>{badge(status)}</div><div className="query-meta"><span>Owner <b>{owner}</b></span><span>Created by <b>{createdBy}</b></span><span>{created}</span></div><div className="thread-messages">{messages.map(([name,role,body,time]) => <div className="thread-message" key={`${name}-${time}`}><div className={`message-avatar ${role.toLowerCase()}`}>{name[0]}</div><div><b>{name} <small>{role}</small></b><p>{body}</p><span>{time}</span></div></div>)}</div><div className="thread-resolution"><b>Resolution</b><span>Open — waiting for warehouse fulfilment confirmation.</span></div></article> }

function DetailLayout({ children, context = true }: { children: React.ReactNode; context?: boolean }) { return <div className="detail-layout">{children}{context && <aside className="context-stack"><section className="panel"><h3>Operational context</h3><div className="context-row"><span>Exception owner</span><b>Warehouse Ops</b></div><div className="context-row"><span>Integration health</span><b className="green-text">Healthy</b></div><div className="context-row"><span>Last sync</span><b>12:18 BST</b></div></section></aside>}</div> }
function Info({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><b className={value.includes("Not provided") ? "not-provided" : ""}>{value}</b></div> }
