"use client";

import { useState } from "react";

const tabs = ["Overview", "Items & Fulfilment", "Shipments", "Documents", "Activity", "Queries", "Integrations"] as const;
type Tab = typeof tabs[number];
const badge = (value: string) => <span className={`pill ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>;

export function OrderDetailTabs({ activeTab, onTabChange }: { activeTab: string; onTabChange: (tab: string) => void }) {
  return <><nav className="detail-tabs" aria-label="Order detail sections">{tabs.map((tab) => <button key={tab} className={activeTab === tab ? "active" : ""} onClick={() => onTabChange(tab)}>{tab}</button>)}</nav><OrderTabContent tab={activeTab as Tab} /></>;
}

function OrderTabContent({ tab }: { tab: Tab }) {
  if (tab === "Overview") return <DetailLayout><section className="panel detail-panel"><h2>Overview</h2><div className="info-grid">{[["Order identifiers", "EU33691 · External ref #SP-36193"], ["Source channel", "Shopify"], ["Order type", "B2C"], ["Customer", "Amelia Wren · amelia@showpo.com"], ["Delivery address", "21 Cloudesley Road, London N1 0HS, United Kingdom"], ["Warehouse", "London Fulfilment"], ["Routing reason", "Available stock + UK Next Day service"], ["Courier / service", "DPD UK · Next Day"], ["Order value", "£148.00"], ["Required dispatch", "21 Aug 2026, 17:00 BST"]].map(([label,value]) => <Info label={label} value={value} key={label} />)}</div></section></DetailLayout>;
  if (tab === "Items & Fulfilment") return <ItemsTab />;
  if (tab === "Shipments") return <DetailLayout><section className="panel detail-panel"><h2>Shipments</h2><div className="shipment-card"><div className="shipment-icon">↗</div><div><span>Shipment reference · SHP-UK-884201</span><b>DPD UK · Next Day</b><p>Latest scan: Awaiting first carrier scan</p></div>{badge("Awaiting First Scan")}</div><div className="info-grid">{[["Courier", "DPD UK"], ["Service", "Next Day"], ["Shipment reference", "SHP-UK-884201"], ["Tracking", "1550 8442 0191"], ["Weight", "0.8 kg"], ["Parcel count", "1"], ["Shipment state", "Awaiting First Scan"], ["Latest scan", "Not provided by carrier yet"]].map(([label,value]) => <Info label={label} value={value} key={label} />)}</div></section></DetailLayout>;
  if (tab === "Documents") return <DetailLayout><section className="panel detail-panel"><h2>Documents</h2><p>Documents stay attached to the order and are explicit when unavailable.</p>{[["Shipping label", "Created by London Fulfilment", "PDF"], ["Commercial invoice", "Not provided by this warehouse", "Unavailable"], ["Customs documents", "Not required for this domestic shipment", "Not required"], ["Packing slip", "Created by London Fulfilment", "PDF"]].map(([name,copy,status]) => <button className="document-row" title={`Opens ${name} when available.`} key={name}><span>▤</span><div><b>{name}</b><small>{copy}</small></div>{badge(status)}<i>→</i></button>)}</section></DetailLayout>;
  if (tab === "Activity") return <DetailLayout><section className="panel detail-panel"><h2>Activity</h2><p>Full immutable audit history across users, system checks and integration events.</p>{[["Quantity mismatch raised", "System · 12:18", "Shipment reconciliation found one unit outstanding."], ["Order despatched", "London Fulfilment · 12:14", "One parcel created; tracking awaits first carrier scan."], ["WMS acknowledged order", "Integration · 10:02", "WMS reference LON-884201 retained."], ["Stock allocated", "System · 09:43", "Three units reserved from London inventory."], ["Order received", "Shopify · 10:15", "Source version 1 captured in Bundle."]].map(([title,by,copy], index) => <div className="timeline" key={title}><i className={index === 0 ? "warn" : ""}/><div><b>{title}</b><small>{by}</small><p>{copy}</p></div></div>)}</section></DetailLayout>;
  if (tab === "Queries") return <DetailLayout><section className="panel detail-panel"><div className="panel-head"><div><h2>Queries</h2><p>Client and support communication remains attached to the order context.</p></div><button className="primary" title="Creates a structured order query with an owner, due time and notes.">+ Raise query</button></div><div className="query-card"><span>QUERY-001</span><div><b>Confirm residual fulfilment plan</b><small>Raised by Amelia Wren · Assigned to Warehouse Ops · Due in 1h 42m</small></div>{badge("Open")}</div><div className="query-message"><b>Amelia Wren</b><small>Can you confirm when the outstanding serum will ship?</small><span>12:24 BST</span></div></section></DetailLayout>;
  return <DetailLayout><section className="panel detail-panel"><h2>Integrations</h2><p>Human-readable technical event trace with safe metadata access.</p>{[["Shopify", "Order received", "10:15:11", "Success"], ["Bundle", "Schema, address and inventory validated", "10:15:38", "Success"], ["London WMS", "Order accepted · LON-884201", "10:16:12", "Success"], ["London WMS", "Despatch event received", "12:14:07", "Success"], ["DPD UK", "Awaiting first carrier scan", "Not provided yet", "Waiting"]].map(([source,event,time,status]) => <div className="trace-row" key={`${source}-${event}`}><span>{source}</span><div><b>{event}</b><small>{time}</small></div>{badge(status)}<button title="Shows event metadata, correlation ID and a safe request/response summary.">View event →</button></div>)}</section></DetailLayout>;
}

function ItemsTab() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const items = [{ name: "Balance Daily Serum", sku: "AA-SER-30", ordered: "2", allocated: "2", shipped: "1", batch: "B-240821", expiry: "31 Aug 2027", location: "LON-A-14-02" }, { name: "Renewal Night Cream", sku: "AA-NCR-50", ordered: "1", allocated: "1", shipped: "1", batch: null, expiry: null, location: null }];
  return <DetailLayout><section className="panel detail-panel"><h2>Items & Fulfilment</h2><p>Expand a SKU to inspect the warehouse-level fulfilment data available to Bundle.</p>{items.map((item) => <div className="sku-block" key={item.sku}><button className="fulfilment-row sku-toggle" onClick={() => setExpanded(expanded === item.sku ? null : item.sku)} aria-expanded={expanded === item.sku}><div className="product-image">{item.name[0]}</div><div className="product-copy"><b>{item.name}</b><small>SKU · {item.sku}</small></div><div><small>ORDERED</small><b>{item.ordered}</b></div><div><small>ALLOCATED</small><b>{item.allocated}</b></div><div><small>SHIPPED</small><b className={item.shipped !== item.ordered ? "amber-text" : ""}>{item.shipped}</b></div><i>{expanded === item.sku ? "⌃" : "⌄"}</i></button>{expanded === item.sku && <div className="warehouse-detail"><h3>Warehouse detail</h3><div className="info-grid"><Info label="Available" value={item.name === "Balance Daily Serum" ? "41" : "Not provided by this warehouse"} /><Info label="Allocated" value={item.allocated} /><Info label="Picked" value={item.shipped} /><Info label="Packed" value={item.shipped} /><Info label="Shipped" value={item.shipped} /><Info label="Batch / lot number" value={item.batch ?? "Not provided by this warehouse"} /><Info label="Expiry date" value={item.expiry ?? "Not provided by this warehouse"} /><Info label="Inventory location" value={item.location ?? "Not provided by this warehouse"} /></div></div>}</div>)}</section></DetailLayout>;
}

function DetailLayout({ children }: { children: React.ReactNode }) { return <div className="detail-layout">{children}<aside className="context-stack"><section className="panel"><h3>Operational context</h3><div className="context-row"><span>Exception owner</span><b>Warehouse Ops</b></div><div className="context-row"><span>Integration health</span><b className="green-text">Healthy</b></div><div className="context-row"><span>Last sync</span><b>12:18 BST</b></div></section></aside></div> }
function Info({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><b className={value.includes("Not provided") ? "not-provided" : ""}>{value}</b></div> }
