"use client";

import { useState } from "react";

const tabs = ["Overview", "Items & Fulfilment", "Shipments", "Documents", "Activity", "Queries", "Integrations"] as const;
type Tab = typeof tabs[number];
const badge = (value: string) => <span className={`pill ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>;

export function OrderDetailTabs({ activeTab, onTabChange }: { activeTab: string; onTabChange: (tab: string) => void }) {
  return <><nav className="detail-tabs" aria-label="Order detail sections">{tabs.map((tab) => <button key={tab} className={activeTab === tab ? "active" : ""} onClick={() => onTabChange(tab)}>{tab}</button>)}</nav><OrderTabContent tab={activeTab as Tab} /></>;
}

function OrderTabContent({ tab }: { tab: Tab }) {
  if (tab === "Overview") return <OverviewTab />;
  if (tab === "Items & Fulfilment") return <ItemsTab />;
  if (tab === "Shipments") return <DetailLayout><section className="panel detail-panel"><h2>Shipments</h2><div className="shipment-card"><div className="shipment-icon">↗</div><div><span>Shipment reference · SHP-UK-884201</span><b>DPD UK · Next Day</b><p>Latest scan: Awaiting first carrier scan</p></div>{badge("Awaiting First Scan")}</div><div className="info-grid">{[["Courier", "DPD UK"], ["Service", "Next Day"], ["Shipment reference", "SHP-UK-884201"], ["Tracking", "1550 8442 0191"], ["Weight", "0.8 kg"], ["Parcel count", "1"], ["Shipment state", "Awaiting First Scan"], ["Latest scan", "Not provided by carrier yet"]].map(([label,value]) => <Info label={label} value={value} key={label} />)}</div></section></DetailLayout>;
  if (tab === "Documents") return <DetailLayout><section className="panel detail-panel"><h2>Documents</h2><p>Documents stay attached to the order and are explicit when unavailable.</p>{[["Shipping label", "Created by London Fulfilment", "PDF"], ["Commercial invoice", "Not provided by this warehouse", "Unavailable"], ["Customs documents", "Not required for this domestic shipment", "Not required"], ["Packing slip", "Created by London Fulfilment", "PDF"]].map(([name,copy,status]) => <button className="document-row" title={`Opens ${name} when available.`} key={name}><span>▤</span><div><b>{name}</b><small>{copy}</small></div>{badge(status)}<i>→</i></button>)}</section></DetailLayout>;
  if (tab === "Activity") return <ActivityTimeline />;
  if (tab === "Queries") return <DetailLayout><section className="panel detail-panel"><div className="panel-head"><div><h2>Queries</h2><p>Client and support communication remains attached to the order context.</p></div><button className="primary" title="Creates a structured order query with an owner, due time and notes.">+ Raise query</button></div><div className="query-card"><span>QUERY-001</span><div><b>Confirm residual fulfilment plan</b><small>Raised by Amelia Wren · Assigned to Warehouse Ops · Due in 1h 42m</small></div>{badge("Open")}</div><div className="query-message"><b>Amelia Wren</b><small>Can you confirm when the outstanding serum will ship?</small><span>12:24 BST</span></div></section></DetailLayout>;
  return <DetailLayout><section className="panel detail-panel"><h2>Integrations</h2><p>Human-readable technical event trace with safe metadata access.</p>{[["Shopify", "Order received", "10:15:11", "Success"], ["Bundle", "Schema, address and inventory validated", "10:15:38", "Success"], ["London WMS", "Order accepted · LON-884201", "10:16:12", "Success"], ["London WMS", "Despatch event received", "12:14:07", "Success"], ["DPD UK", "Awaiting first carrier scan", "Not provided yet", "Waiting"]].map(([source,event,time,status]) => <div className="trace-row" key={`${source}-${event}`}><span>{source}</span><div><b>{event}</b><small>{time}</small></div>{badge(status)}<button title="Shows event metadata, correlation ID and a safe request/response summary.">View event →</button></div>)}</section></DetailLayout>;
}

function ItemsTab() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const items = [{ name: "Balance Daily Serum", sku: "AA-SER-30", ordered: "2", allocated: "2", shipped: "1", batch: "B-240821", expiry: "31 Aug 2027", location: "LON-A-14-02" }, { name: "Renewal Night Cream", sku: "AA-NCR-50", ordered: "1", allocated: "1", shipped: "1", batch: null, expiry: null, location: null }];
  return <DetailLayout><section className="panel detail-panel"><h2>Items & Fulfilment</h2><p>Expand a SKU to inspect the warehouse-level fulfilment data available to Bundle.</p>{items.map((item) => <div className="sku-block" key={item.sku}><button className="fulfilment-row sku-toggle" onClick={() => setExpanded(expanded === item.sku ? null : item.sku)} aria-expanded={expanded === item.sku}><div className="product-image">{item.name[0]}</div><div className="product-copy"><b>{item.name}</b><small>SKU · {item.sku}</small></div><div><small>ORDERED</small><b>{item.ordered}</b></div><div><small>ALLOCATED</small><b>{item.allocated}</b></div><div><small>SHIPPED</small><b className={item.shipped !== item.ordered ? "amber-text" : ""}>{item.shipped}</b></div><i>{expanded === item.sku ? "⌃" : "⌄"}</i></button>{expanded === item.sku && <div className="warehouse-detail"><h3>Warehouse detail</h3><div className="info-grid"><Info label="Available" value={item.name === "Balance Daily Serum" ? "41" : "Not provided by this warehouse"} /><Info label="Allocated" value={item.allocated} /><Info label="Picked" value={item.shipped} /><Info label="Packed" value={item.shipped} /><Info label="Shipped" value={item.shipped} /><Info label="Batch / lot number" value={item.batch ?? "Not provided by this warehouse"} /><Info label="Expiry date" value={item.expiry ?? "Not provided by this warehouse"} /><Info label="Inventory location" value={item.location ?? "Not provided by this warehouse"} /></div></div>}</div>)}</section></DetailLayout>;
}

function OverviewTab() { return <DetailLayout context={false}><section className="panel detail-panel"><div className="panel-head"><div><h2>Overview</h2><p>Order information is synchronised from its source of truth.</p></div></div><section className="source-of-truth"><div><small>Source</small><b>Shopify</b><span>Last synced 3 minutes ago</span></div><button title="Opens this order in Shopify.">Open in Shopify ↗</button></section><div className="source-message"><b>Changes to this order should be made in Shopify before warehouse acknowledgement.</b><p>Bundle will re-sync and revalidate eligible changes automatically.</p></div><div className="info-grid">{[["Order identifiers", "EU33691 · External ref #SP-36193"], ["Source channel", "Shopify"], ["Order type", "B2C"], ["Customer", "Amelia Wren · amelia@showpo.com"], ["Delivery address", "21 Cloudesley Road, London N1 0HS, United Kingdom"], ["Warehouse", "London Fulfilment"], ["Routing reason", "Available stock + UK Next Day service"], ["Courier / service", "DPD UK · Next Day"], ["Order value", "£148.00"], ["Required dispatch", "21 Aug 2026, 17:00 BST"]].map(([label,value]) => <Info label={label} value={value} key={label} />)}</div></section><aside className="context-stack"><section className="panel override-context"><h3>Operational overrides</h3><p>Internal Wayfindr users may apply authorised overrides only where the order state, lock point and permission allow it.</p><ul><li>Every override is audited with old/new values and actor.</li><li>Bundle validates downstream propagation.</li><li>A failed propagation creates an exception.</li></ul><button className="outline wide" title="Shows permitted internal overrides for this order state.">View permitted overrides</button></section><section className="panel source-rules"><h3>Source editability</h3><div><b>Storefront / API orders</b><span>Edit in source before acknowledgement.</span></div><div><b>Manual / bulk orders</b><span>Editability depends on creator, state and lock point.</span></div></section></aside></DetailLayout> }

type ActivityFilter = "All" | "Order" | "Warehouse" | "Shipment" | "User Actions" | "Integration" | "Exceptions";
const activityEvents: Array<{ time: string; title: string; actor: string; type: ActivityFilter; detail: string; change?: [string, string, string] }> = [
  { time: "12:18:04", title: "Partial fulfilment detected", actor: "Bundle · System", type: "Exceptions", detail: "Shipment reconciliation found 1 unit outstanding." },
  { time: "12:14:32", title: "Shipment despatched", actor: "Scale3PL · Mintsoft", type: "Shipment", detail: "Parcel created. Tracking awaiting first carrier scan." },
  { time: "10:02:11", title: "WMS acknowledged order", actor: "Scale3PL · API", type: "Warehouse", detail: "Warehouse reference: SC-354592" },
  { time: "09:51:24", title: "Delivery address changed", actor: "Harry Emerson · Wayfindr", type: "User Actions", detail: "Order amendment validated and forwarded to the warehouse.", change: ["Postcode", "BH12 2JQ", "BH12 3AB"] },
  { time: "09:43:03", title: "Inventory allocated", actor: "Bundle · Inventory", type: "Order", detail: "3 units reserved." },
  { time: "09:42:58", title: "Order validation passed", actor: "Bundle", type: "Order", detail: "Schema, address and SKU checks completed successfully." },
  { time: "09:42:41", title: "Order received", actor: "Shopify", type: "Integration", detail: "Source order SP-36193 ingested into Bundle." },
];

function ActivityTimeline() {
  const [filter, setFilter] = useState<ActivityFilter>("All");
  const events = activityEvents.filter((event) => filter === "All" || event.type === filter);
  return <DetailLayout><section className="panel detail-panel activity-panel"><div className="panel-head"><div><h2>Activity</h2><p>Immutable chronological audit trail. Every operational change has an actor, timestamp and source.</p></div><span className="audit-lock">Immutable</span></div><div className="activity-filters" role="tablist">{(["All", "Order", "Warehouse", "Shipment", "User Actions", "Integration", "Exceptions"] as ActivityFilter[]).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="activity-timeline">{events.map((event) => <article className={`activity-event ${event.type.toLowerCase().replaceAll(" ", "-")}`} key={`${event.time}-${event.title}`}><time>{event.time}</time><i/><div><b>{event.title}</b><span>{event.actor}</span><p>{event.detail}</p>{event.change && <div className="change-record"><small>{event.change[0]}</small><b>{event.change[1]} <em>→</em> {event.change[2]}</b></div>}</div></article>)}</div>{events.length === 0 && <div className="empty-state">No activity matches this filter.</div>}</section></DetailLayout>;
}

function DetailLayout({ children, context = true }: { children: React.ReactNode; context?: boolean }) { return <div className="detail-layout">{children}{context && <aside className="context-stack"><section className="panel"><h3>Operational context</h3><div className="context-row"><span>Exception owner</span><b>Warehouse Ops</b></div><div className="context-row"><span>Integration health</span><b className="green-text">Healthy</b></div><div className="context-row"><span>Last sync</span><b>12:18 BST</b></div></section></aside>}</div> }
function Info({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><b className={value.includes("Not provided") ? "not-provided" : ""}>{value}</b></div> }
