"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Queue = "All Orders" | "Action Required" | "Stalled" | "Push Failed" | "On Hold" | "SLA At Risk" | "Cancellation Pending" | "Partial Fulfilment";
type Order = { id: string; client: string; state: string; wms: string; shipment: string; sla: string; warehouse: string; issue?: string; tags: string[] };

const queues: Array<[Queue, number]> = [["All Orders", 1248], ["Action Required", 18], ["Stalled", 6], ["Push Failed", 3], ["On Hold", 11], ["SLA At Risk", 7], ["Cancellation Pending", 2], ["Partial Fulfilment", 5]];
const orders: Order[] = [
  { id: "BW-10482", client: "Aster & Ash", state: "Ready", wms: "Sent", shipment: "Awaiting scan", sla: "Within SLA", warehouse: "London · GB", tags: [] },
  { id: "BW-10481", client: "Canyon Club", state: "In Fulfilment", wms: "Pick started", shipment: "Not created", sla: "At risk", warehouse: "Rotterdam · NL", tags: ["SLA At Risk"] },
  { id: "BW-10480", client: "Aster & Ash", state: "Validating", wms: "Not sent", shipment: "Not created", sla: "Breached", warehouse: "—", issue: "Address invalid", tags: ["Action Required"] },
  { id: "BW-10479", client: "Kanso Studio", state: "In Transit", wms: "Despatched", shipment: "In transit", sla: "Within SLA", warehouse: "Sydney · AU", tags: [] },
  { id: "BW-10478", client: "Canyon Club", state: "On Hold", wms: "Acknowledged", shipment: "Awaiting scan", sla: "Paused", warehouse: "Los Angeles · US", issue: "Missing SKU", tags: ["On Hold", "Action Required"] },
  { id: "BW-10477", client: "Aster & Ash", state: "Partially fulfilled", wms: "Despatched", shipment: "Awaiting scan", sla: "At risk", warehouse: "London · GB", issue: "Quantity mismatch", tags: ["Partial Fulfilment", "Action Required", "SLA At Risk"] },
  { id: "BW-10471", client: "Canyon Club", state: "Ready", wms: "Push failed", shipment: "Not created", sla: "At risk", warehouse: "Los Angeles · US", issue: "WMS push failed", tags: ["Push Failed", "Action Required", "SLA At Risk"] },
  { id: "BW-10463", client: "Kanso Studio", state: "Cancellation Pending", wms: "Awaiting cancellation", shipment: "Awaiting scan", sla: "At risk", warehouse: "Rotterdam · NL", issue: "Awaiting warehouse confirmation", tags: ["Cancellation Pending", "Action Required"] },
  { id: "BW-10458", client: "Aster & Ash", state: "In Fulfilment", wms: "Acknowledged", shipment: "Not created", sla: "Within SLA", warehouse: "London · GB", issue: "Waiting for WMS acknowledgement", tags: ["Stalled"] },
];

const classFor = (value: string) => value.toLowerCase().replaceAll(" ", "-");
const pill = (value: string) => <span className={`pill ${classFor(value)}`}>{value}</span>;

function AppShell({ children, detail = false }: { children: React.ReactNode; detail?: boolean }) {
  const [clientOpen, setClientOpen] = useState(false);
  return <main className="oms-shell"><header className="bundle-topnav"><Link href="/orders" className="bundle-logo"><span>b</span><b>bundle</b><small>by wayfindr</small></Link><nav aria-label="Main navigation"><button title="Dashboard is outside the scope of this Order Management prototype.">Dashboard</button><Link className="nav-active" href="/orders">Orders</Link><button title="Returns is outside the scope of this Order Management prototype.">Returns</button><button title="Inventory is outside the scope of this Order Management prototype.">Inventory</button><button title="ASN is outside the scope of this Order Management prototype.">ASN</button><button title="Shipments is outside the scope of this Order Management prototype.">Shipments</button><button title="Settings is outside the scope of this Order Management prototype.">Settings</button></nav><div className="topnav-right"><div className="client-select"><button title="Switches client scope for internal Wayfindr users." onClick={() => setClientOpen((current) => !current)}>All Clients <span>⌄</span></button>{clientOpen && <div className="client-menu"><button onClick={() => setClientOpen(false)}>All Clients</button><button onClick={() => setClientOpen(false)}>Aster & Ash</button><button onClick={() => setClientOpen(false)}>Canyon Club</button></div>}</div><button title="Shows notifications." className="top-notification">●<i>3</i></button><div className="avatar top-avatar">EM</div></div></header><section className="oms-content">{children}</section></main>;
}

function Header({ title, copy, back }: { title: string; copy: string; back?: boolean }) {
  return <header className="oms-head"> <div>{back && <Link href="/orders" className="back-link">← All orders</Link>}<h1>{title}</h1><p>{copy}</p></div><div className="head-actions"><button title="Searches the current order workbench." className="icon-button">⌕</button></div></header>;
}

export function OrderWorkbench() {
  const [queue, setQueue] = useState<Queue>("All Orders");
  const [search, setSearch] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const filtered = useMemo(() => orders.filter((order) => (queue === "All Orders" || order.tags.includes(queue)) && `${order.id} ${order.client} ${order.warehouse} ${order.issue ?? ""}`.toLowerCase().includes(search.toLowerCase())), [queue, search]);
  return <AppShell><Header title="Order Management" copy="One operational workbench for every order, its progress and its next action." />
    <section className="oms-summary"><article><span>Orders in flight</span><b>1,248</b><small>↑ 12.4% this week</small></article><article><span>Action required</span><b>18</b><small className="red-text">6 high priority</small></article><article><span>Fulfilment SLA</span><b>96.8%</b><small>Target 95% · On track</small></article><article><span>Inventory health</span><b>99.1%</b><small>Fresh across 4 warehouses</small></article></section>
    <section className="panel pipeline-panel"><div className="panel-head"><div><h2>Order pipeline</h2><p>Where every order is in the canonical Bundle lifecycle.</p></div><button title="Opens the full lifecycle and state-transition definitions." className="text-button">View lifecycle →</button></div><div className="pipeline">{[["Validating", 34], ["Ready", 116], ["In Fulfilment", 621], ["Fulfilled", 75], ["In Transit", 283], ["Delivered", 96], ["Invoiced", 23]].map(([name,count], index) => <div className="pipeline-step" key={String(name)}><span>{String(index + 1).padStart(2, "0")}</span><b>{String(name)}</b><strong>{count}</strong></div>)}</div><div className="pipeline-branches"><span>11 On Hold</span><span>5 Partial fulfilment</span><span>2 Cancellation pending</span><span>18 with exceptions</span></div></section>
    <section className="orders-workbench"><div className="panel-head"><div><h2>All operational orders</h2><p>Search, segment and act without leaving Order Management.</p></div><div className="create-wrap"><button title="Shows options to create one manual order or upload an order file." className="primary" onClick={() => setCreateOpen((current) => !current)}>+ Create order ⌄</button>{createOpen && <div className="create-menu"><button title="Creates a single manual order then runs normal validation.">Manual order</button><button title="Opens a bulk-upload drawer with row-level validation.">Bulk upload orders</button></div>}</div></div>
      <div className="queue-tabs" role="tablist">{queues.map(([name,count]) => <button role="tab" aria-selected={queue === name} className={queue === name ? "active" : ""} onClick={() => setQueue(name)} title={`Shows the ${name} operational queue.`}>{name}<b>{count}</b></button>)}</div>
      <div className="toolbar"><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order, reference, customer or warehouse…" /></label><button title="Shows filters for order state, warehouse, client, SLA, courier and exception ownership." className="filter" onClick={() => setFiltersOpen((current) => !current)}>☷ Filters <span>2</span></button><button title="Lets the user choose which order fields are visible in the workbench." className="filter">Columns</button></div>
      {filtersOpen && <div className="filter-drawer"><b>Active filters</b><span>Client: All clients</span><span>Warehouse: All warehouses</span><span>SLA: At risk or breached</span><button onClick={() => setFiltersOpen(false)}>Done</button></div>}
      <OrderTable rows={filtered} />
    </section>
  </AppShell>;
}

function OrderTable({ rows }: { rows: Order[] }) { return <div className="orders-table-wrap"><div className="table-meta">{rows.length} matching orders <span>•</span> Last updated just now <button title="Exports the visible queue and selected columns.">Export ↓</button></div><table className="orders-table"><thead><tr><th>Order</th><th>Client</th><th>Order state</th><th>WMS state</th><th>Shipment</th><th>SLA</th><th>Warehouse</th><th>Exception / work item</th></tr></thead><tbody>{rows.map((order) => <tr key={order.id}><td><Link href={`/orders/${order.id}`}><b>#{order.id}</b><small>Shopify · 14 min ago</small></Link></td><td>{order.client}</td><td>{pill(order.state)}</td><td>{order.wms}</td><td>{order.shipment}</td><td>{pill(order.sla)}</td><td>{order.warehouse}</td><td>{order.issue ? <Link className="order-issue" href={`/orders/${order.id}`}>{order.issue} →</Link> : <span className="quiet">—</span>}</td></tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state">No orders match this queue and search. Clear the search or choose another operational view.</div>}</div> }

const detailTabs = ["Order information", "Items & Fulfilment", "Shipment", "Activity", "Documents", "Queries", "Integration trace"] as const;
type DetailTab = (typeof detailTabs)[number];

export function OrderDetail({ orderId }: { orderId: string }) {
  const [tab, setTab] = useState<DetailTab>("Order information");
  const [actionOpen, setActionOpen] = useState(false);
  const order = orders.find((item) => item.id === orderId) ?? orders[5];
  return <AppShell detail><Header back title={`Order #${order.id}`} copy={`${order.client} · Shopify · Created today at 09:42 BST`} />
    <section className="state-overview"><div><small>ORDER STATE</small>{pill(order.state)}</div><i>›</i><div><small>WMS STATE</small><b>{order.wms}</b></div><i>›</i><div><small>SHIPMENT STATE</small><b>{order.shipment}</b></div><i>›</i><div><small>SLA</small>{pill(order.sla)}</div><div className="route-reason"><small>ROUTED TO</small><b>{order.warehouse}</b><span>Stock + delivery rule matched</span></div></section>
    {order.issue && <section className="detail-alert"><b>!</b><div><strong>{order.issue} needs review</strong><p>Bundle has surfaced a structured work item with ownership, a reason and permitted resolution actions.</p></div><button title="Opens the contextual resolution drawer for this order." onClick={() => setActionOpen(true)}>Review resolution →</button></section>}
    <div className="detail-actions"><button title="Places the order on hold, records a reason and pauses progression." className="outline" onClick={() => setActionOpen(true)}>Hold</button><button title="Shows eligible alternate warehouses and reruns routing validation." className="outline" onClick={() => setActionOpen(true)}>Re-route</button><button title="Shows only safe actions permitted by the current state and user role." className="primary" onClick={() => setActionOpen(true)}>Operational actions ⌄</button></div>
    <nav className="detail-tabs" aria-label="Order detail sections">{detailTabs.map((name) => <button className={tab === name ? "active" : ""} onClick={() => setTab(name)}>{name}</button>)}</nav>
    <DetailPanel tab={tab} order={order} />
    {actionOpen && <div className="modal-backdrop" role="presentation" onClick={() => setActionOpen(false)}><section className="action-drawer" role="dialog" aria-modal="true" aria-label="Operational actions" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={() => setActionOpen(false)}>×</button><span className="eyebrow">STATE-AWARE ACTIONS</span><h2>Allowed operational actions</h2><p>Available actions are controlled by the order&apos;s state, WMS lock points and your role.</p>{[["Resolve quantity mismatch", "Reconcile short shipment and create a residual fulfilment part."], ["Place on hold", "Pause workflow with a reason; notify the warehouse if it supports holds."], ["Raise an order query", "Create a structured query with owner, due time and supporting notes."], ["Open integration trace", "Inspect the human-readable Shopify → Bundle → WMS event trail."]].map(([title,copy]) => <button className="drawer-action" title={copy} key={title}><b>{title}</b><span>{copy}</span><i>→</i></button>)}</section></div>}
  </AppShell>;
}

function DetailPanel({ tab, order }: { tab: DetailTab; order: Order }) {
  if (tab === "Order information") return <div className="detail-layout"><section className="panel detail-panel"><h2>Order information</h2><div className="info-grid">{[["Client", order.client], ["External reference", "AA-93831"], ["Order type", "B2C"], ["Source", "Shopify"], ["Customer", "Amelia Wren"], ["Email", "amelia@asterandash.com"], ["Delivery address", "21 Cloudesley Road, London N1 0HS"], ["Order value", "£148.00"], ["Required despatch", "Today, 17:00"], ["Routing rationale", "London stock + Next Day service"]].map(([label,value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div></section><ContextPanel /></div>;
  if (tab === "Items & Fulfilment") return <div className="detail-layout"><section className="panel detail-panel"><h2>Items & Fulfilment</h2><p>Line-level quantities make partial fulfilment visible and actionable.</p>{[["Balance Daily Serum", "AA-SER-30", "2", "2", "1"], ["Renewal Night Cream", "AA-NCR-50", "1", "1", "1"]].map(([name,sku,ordered,allocated,shipped]) => <div className="fulfilment-row" key={sku}><div className="product-image">{name[0]}</div><div className="product-copy"><b>{name}</b><small>SKU · {sku}</small></div><div><small>ORDERED</small><b>{ordered}</b></div><div><small>ALLOCATED</small><b>{allocated}</b></div><div><small>SHIPPED</small><b className={shipped !== ordered ? "amber-text" : ""}>{shipped}</b></div><button title="Expands warehouse quantities, batch/lot and expiry details.">⌄</button></div>)}</section><ContextPanel /></div>;
  if (tab === "Shipment") return <div className="detail-layout"><section className="panel detail-panel"><h2>Shipment information</h2><div className="shipment-card"><div className="shipment-icon">↗</div><div><span>DPD UK · Next Day</span><b>Awaiting first carrier scan</b><p>Shipment created at 12:14 BST. Bundle keeps fulfilment and tracking states separate.</p></div>{pill("Awaiting scan")}</div><div className="info-grid"><div><small>Tracking number</small><b>Pending carrier scan</b></div><div><small>Parcel count</small><b>1 parcel</b></div><div><small>Total weight</small><b>0.8 kg</b></div><div><small>Despatched</small><b>Today, 12:14 BST</b></div></div></section><ContextPanel /></div>;
  if (tab === "Activity") return <div className="detail-layout"><section className="panel detail-panel"><h2>Activity & audit history</h2><p>Immutable record of user actions, system validations and integration events.</p>{[["Order partially fulfilled", "System · 12:18", "Shipment reconciliation found one unit outstanding."], ["Order despatched", "London Fulfilment · 12:14", "One parcel created; tracking awaits first carrier scan."], ["WMS acknowledged order", "Integration · 10:02", "WMS reference: LON-884201"], ["Stock allocated", "System · 09:43", "Three units reserved from London inventory."]].map(([title,by,copy], index) => <div className="timeline" key={title}><i className={index === 0 ? "warn" : ""}/><div><b>{title}</b><small>{by}</small><p>{copy}</p></div></div>)}</section><ContextPanel /></div>;
  if (tab === "Documents") return <div className="detail-layout"><section className="panel detail-panel"><h2>Documents</h2><p>Labels, commercial invoices and customs records linked to the order.</p>{[["Shipping label", "Created by London Fulfilment", "PDF"], ["Commercial invoice", "Awaiting invoice readiness", "Pending"], ["Packing slip", "Created by London Fulfilment", "PDF"]].map(([name,copy,status]) => <button className="document-row" title={`Opens ${name} when available.`} key={name}><span>▤</span><div><b>{name}</b><small>{copy}</small></div>{pill(status)}<i>→</i></button>)}</section><ContextPanel /></div>;
  if (tab === "Queries") return <div className="detail-layout"><section className="panel detail-panel"><div className="panel-head"><div><h2>Queries</h2><p>Order-level operational questions stay with the order, not in a separate support tool.</p></div><button title="Creates a structured order query with type, owner, due time and notes." className="primary">+ Raise query</button></div><div className="query-card"><span>QUERY-001</span><div><b>Confirm residual fulfilment plan</b><small>Assigned to Warehouse Ops · Due in 1h 42m</small></div>{pill("Open")}</div></section><ContextPanel /></div>;
  return <div className="detail-layout"><section className="panel detail-panel"><h2>Integration trace</h2><p>Human-readable evidence across storefront, Bundle, WMS and carrier events.</p>{[["Shopify", "Order received", "09:42:11", "Success"], ["Bundle", "Schema, address and inventory validated", "09:43:02", "Success"], ["London WMS", "Order accepted · LON-884201", "10:02:19", "Success"], ["London WMS", "Despatch event received", "12:14:07", "Success"], ["DPD UK", "Awaiting first carrier scan", "—", "Pending"]].map(([source,event,time,status]) => <div className="trace-row" key={`${source}-${event}`}><span>{source}</span><div><b>{event}</b><small>{time}</small></div>{pill(status)}<button title="Shows event metadata, correlation ID and a safe request/response summary.">View event →</button></div>)}</section><ContextPanel /></div>;
}

function ContextPanel() { return <aside className="context-stack"><section className="panel"><h3>Order controls</h3><p>Actions are state-aware, permissioned and always audited.</p><button title="Shows safe actions for this order state." className="outline wide">View allowed actions</button><button title="Creates an order-level operational query." className="text-button">Raise a query →</button></section><section className="panel"><h3>Operational context</h3><div className="context-row"><span>Exception owner</span><b>Warehouse Ops</b></div><div className="context-row"><span>Integration health</span><b className="green-text">Healthy</b></div><div className="context-row"><span>Last sync</span><b>12:18 BST</b></div></section></aside>;
}
