"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AppShell, Header, useBundleScope } from "./order-management";
import { LogicLabel, LogicTooltip } from "./logic-tooltip";

type View = "All Orders" | "Action Required" | "Stalled" | "Push Failed" | "On Hold" | "SLA At Risk" | "Cancellation Pending" | "Partial Fulfilment";
type Order = { id: string; client: string; type: string; state: string; wms: string; shipment: string; sla: string; warehouse: string; exception: string; owner: string; updated: string; tags: View[]; integration: string; country: string; courier: string; source: string; created: string; despatch: string };

const views: Array<[View, number]> = [["All Orders", 1248], ["Action Required", 18], ["Stalled", 6], ["Push Failed", 3], ["On Hold", 11], ["SLA At Risk", 7], ["Cancellation Pending", 2], ["Partial Fulfilment", 5]];
const viewLogic: Partial<Record<View, { what: string; why: string; logic: string }>> = {
  "Action Required": { what: "Orders with an active exception needing a primary owner.", why: "Puts operational recovery ahead of passive monitoring.", logic: "Prioritised by severity, SLA impact and exception age." },
  Stalled: { what: "An expected operational event has not arrived in time.", why: "Identifies silent failures before they become breaches.", logic: "For example, a Ready order without WMS acknowledgement beyond the configured client threshold." },
  "Push Failed": { what: "A WMS handoff did not complete.", why: "Technical recovery must be visible without duplicating orders.", logic: "A retry is available only for retryable failures and is idempotent." },
  "On Hold": { what: "A genuine temporary pause state.", why: "Prevents cancelling and recreating orders simply to pause fulfilment.", logic: "The reason, actor and WMS propagation outcome are recorded." },
  "SLA At Risk": { what: "Orders likely to miss a time-based commitment.", why: "Enables intervention before a breach.", logic: "Calculated from the configured client SLA and the next expected event." },
  "Cancellation Pending": { what: "A cancellation request awaiting downstream confirmation.", why: "After WMS acceptance, cancellation is a request workflow, not an instant state change.", logic: "Bundle marks Cancelled only after the warehouse confirms; it never assumes success." },
  "Partial Fulfilment": { what: "Some, but not all, ordered quantity has shipped.", why: "Outstanding quantity must remain operationally visible.", logic: "0 < shipped quantity < ordered quantity; the residual follows backorder or residual-fulfilment configuration." },
};
const pipelineLogic: Record<string, { what: string; why: string; logic: string }> = {
  Validating: { what: "Order received but not released to WMS.", why: "Catches preventable failures before warehouse handoff.", logic: "Validate required data, address, SKU, inventory and routing. Pass → Ready; blocking issue → remain Validating or an appropriate hold/exception." },
  Ready: { what: "Validation complete and eligible for WMS handoff.", why: "Separates a valid order from one the warehouse has accepted.", logic: "Enters the WMS push cycle and moves to In Fulfilment only after WMS acknowledgement." },
  "In Fulfilment": { what: "WMS accepted responsibility for physical fulfilment.", why: "An API send does not equal warehouse acceptance.", logic: "Triggered only by WMS acknowledgement; picking, picked, packed and despatched remain WMS states beneath it." },
  Fulfilled: { what: "Warehouse fulfilment is complete but carrier possession is unproven.", why: "Warehouse despatch and carrier possession are different events.", logic: "Ordered and shipped quantity must reconcile; remains Fulfilled until a valid carrier first scan." },
  "In Transit": { what: "Carrier possession and movement are confirmed.", why: "Stops shipment progression being inferred from a warehouse event.", logic: "Triggered only by the first recognised carrier scan." },
  Delivered: { what: "Carrier has confirmed delivery.", why: "Provides a consistent end-of-delivery event across couriers.", logic: "Driven by a recognised delivered carrier event." },
};
const summaryLogic: Record<string, { what: string; why: string; logic: string }> = {
  "Action Required": viewLogic["Action Required"]!,
  "SLA At Risk": viewLogic["SLA At Risk"]!,
  "Fulfilment SLA": { what: "Share of orders meeting the configured fulfilment commitment.", why: "Shows whether the fulfilment network is operating to service expectation.", logic: "Calculated against required dispatch commitments; at-risk and breached orders remain visible separately." },
};
const tableLogic: Record<string, { what: string; why: string; logic: string }> = {
  "Order State": { what: "High-level Bundle order lifecycle.", why: "Keeps workflow consistent across warehouses.", logic: "It is independent from WMS, Shipment, SLA and Exception states." },
  "WMS State": { what: "Canonical warehouse execution state.", why: "Normalises warehouse-specific terminology.", logic: "Mapped from WMS events without creating extra order lifecycle stages." },
  "Shipment State": { what: "Carrier and final-mile progress.", why: "Carrier possession needs distinct visibility.", logic: "Updated from shipment and recognised carrier events." },
  SLA: { what: "Time-based operational commitment.", why: "Highlights risk before a breach.", logic: "Can be At Risk while integrations are healthy." },
  Exception: { what: "Structured operational issue.", why: "Makes recovery, ownership and audit explicit.", logic: "Includes type, reason, owner, timestamp and resolution path." },
  Owner: { what: "One primary responsible party.", why: "Avoids ambiguous shared accountability.", logic: "Must be Client, Wayfindr, Warehouse or Tech; a separate Assignee can identify a person or team." },
};
const records: Order[] = [
  { id: "BW-10482", client: "Aster & Ash", type: "B2C", state: "Ready", wms: "Sent", shipment: "Awaiting scan", sla: "Within SLA", warehouse: "London", exception: "—", owner: "—", updated: "2m ago", tags: ["All Orders"], integration: "Healthy", country: "GB", courier: "DPD UK", source: "Shopify", created: "Today, 10:14", despatch: "Today, 17:00" },
  { id: "BW-10481", client: "Canyon Club", type: "B2B", state: "In Fulfilment", wms: "Pick started", shipment: "Not created", sla: "At risk", warehouse: "Rotterdam", exception: "SLA at risk", owner: "Wayfindr", updated: "4m ago", tags: ["All Orders", "SLA At Risk", "Action Required"], integration: "Healthy", country: "NL", courier: "DHL", source: "ERP", created: "Today, 10:02", despatch: "Today, 14:00" },
  { id: "BW-10480", client: "Aster & Ash", type: "B2C", state: "Validating", wms: "Not sent", shipment: "Not created", sla: "Breached", warehouse: "—", exception: "Address invalid", owner: "Client", updated: "12m ago", tags: ["All Orders", "Action Required"], integration: "Blocked", country: "GB", courier: "—", source: "Shopify", created: "Today, 09:42", despatch: "Today, 13:00" },
  { id: "BW-10479", client: "Kanso Studio", type: "B2C", state: "In Transit", wms: "Despatched", shipment: "In transit", sla: "Within SLA", warehouse: "Sydney", exception: "—", owner: "—", updated: "14m ago", tags: ["All Orders"], integration: "Healthy", country: "AU", courier: "AusPost", source: "WooCommerce", created: "Today, 09:36", despatch: "Today, 12:00" },
  { id: "BW-10478", client: "Canyon Club", type: "Subscription", state: "On Hold", wms: "Acknowledged", shipment: "Awaiting scan", sla: "Paused", warehouse: "Los Angeles", exception: "Missing SKU", owner: "Client", updated: "18m ago", tags: ["All Orders", "On Hold", "Action Required"], integration: "Healthy", country: "US", courier: "UPS", source: "API", created: "Today, 09:31", despatch: "Tomorrow, 12:00" },
  { id: "BW-10477", client: "Aster & Ash", type: "B2C", state: "Partially fulfilled", wms: "Despatched", shipment: "Awaiting scan", sla: "At risk", warehouse: "London", exception: "Quantity mismatch", owner: "Warehouse", updated: "22m ago", tags: ["All Orders", "Partial Fulfilment", "Action Required", "SLA At Risk"], integration: "Healthy", country: "GB", courier: "DPD UK", source: "Shopify", created: "Today, 09:22", despatch: "Today, 12:00" },
  { id: "BW-10471", client: "Canyon Club", type: "B2B", state: "Ready", wms: "Push failed", shipment: "Not created", sla: "At risk", warehouse: "Los Angeles", exception: "WMS push failed", owner: "Tech", updated: "28m ago", tags: ["All Orders", "Push Failed", "Action Required", "SLA At Risk"], integration: "Failed", country: "US", courier: "FedEx", source: "ERP", created: "Today, 09:03", despatch: "Today, 11:00" },
  { id: "BW-10463", client: "Kanso Studio", type: "B2C", state: "Cancellation Pending", wms: "Awaiting cancellation", shipment: "Awaiting scan", sla: "At risk", warehouse: "Rotterdam", exception: "Awaiting confirmation", owner: "Warehouse", updated: "41m ago", tags: ["All Orders", "Cancellation Pending", "Action Required"], integration: "Healthy", country: "DE", courier: "DHL", source: "Shopify", created: "Today, 08:42", despatch: "Today, 10:30" },
  { id: "BW-10458", client: "Aster & Ash", type: "B2C", state: "In Fulfilment", wms: "Acknowledged", shipment: "Not created", sla: "Within SLA", warehouse: "London", exception: "No WMS event", owner: "Tech", updated: "1h ago", tags: ["All Orders", "Stalled"], integration: "Stale", country: "GB", courier: "DPD UK", source: "Shopify", created: "Today, 08:14", despatch: "Today, 15:00" },
];

const badge = (value: string) => <span className={`pill ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>;
const optionalFields = ["Integration State", "Country", "Courier", "Source", "Created", "Required Despatch"] as const;
type OptionalField = typeof optionalFields[number];
type CreateMode = "single" | "bulk" | null;

export function OrdersWorkbench() {
  return <AppShell><OrdersWorkbenchContent /></AppShell>;
}

function OrdersWorkbenchContent() {
  const { clientScoped } = useBundleScope();
  const [view, setView] = useState<View>("All Orders");
  const [search, setSearch] = useState("");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [columnsOpen, setColumnsOpen] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [createMode, setCreateMode] = useState<CreateMode>(null);
  const [visibleOptional, setVisibleOptional] = useState<OptionalField[]>([]);
  const filtered = useMemo(() => records.filter((record) => (view === "All Orders" || record.tags.includes(view)) && Object.values(record).join(" ").toLowerCase().includes(search.toLowerCase())), [view, search]);
  const toggleColumn = (field: OptionalField) => setVisibleOptional((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]);
  return <><Header title="Order Management" copy="Monitor, investigate and manage orders across your fulfilment network." />
    <section className="workbench-summary"><SummaryCard label="Orders Today" value="1,248" detail="Across 4 warehouses" /><SummaryCard label="Action Required" value="18" detail="6 high priority" warn /><SummaryCard label="SLA At Risk" value="7" detail="2 within 1 hour" warn /><SummaryCard label="Fulfilment SLA" value="96.8%" detail="Target 95%" /></section>
    <section className="panel canonical-pipeline"><div className="panel-head"><div><h2><LogicLabel title="Order pipeline" what="The canonical high-level Bundle order lifecycle." why="V1 Created, In Progress and Finalised states are too broad for operational control." logic="The lifecycle is centrally controlled. WMS, Shipment, Integration, SLA and Exception are independent dimensions, not extra lifecycle stages.">Order pipeline</LogicLabel></h2><p>Canonical Bundle lifecycle with operational signals surfaced in context.</p></div></div><div className="canonical-stages">{[["Validating", "12 orders", "3 require attention"], ["Ready", "89 orders", "1 routing review"], ["In Fulfilment", "184 orders", "2 push failures · 7 SLA at risk"], ["Fulfilled", "71 orders", "4 awaiting first scan"], ["In Transit", "243 orders", "2 carrier exceptions"], ["Delivered", "96 orders", "All within SLA"]].map(([stage,count,signal], index) => <div className="canonical-stage" key={stage}><span><LogicLabel title={stage} {...pipelineLogic[stage]}>{stage}</LogicLabel></span><b>{count}</b><small className={signal.includes("require") || signal.includes("failure") || signal.includes("risk") ? "signal-warning" : ""}>{signal}</small>{index < 5 && <i>→</i>}</div>)}</div></section>
    <section className="orders-workbench dense-workbench"><div className="panel-head"><div><h2>Orders</h2><p>Saved views filter this same operational table.</p></div><div className="create-wrap"><button className="primary" onClick={() => setCreateOpen((current) => !current)}>+ Create Order <span>⌄</span></button>{createOpen && <div className="create-menu"><button onClick={() => { setCreateMode("single"); setCreateOpen(false); }}>Create single order</button><button onClick={() => { setCreateMode("bulk"); setCreateOpen(false); }}>Bulk upload</button></div>}</div></div>
      <div className="queue-tabs" role="tablist">{views.map(([name,count]) => <span className="view-control" key={name}><button role="tab" aria-selected={view === name} className={view === name ? "active" : ""} onClick={() => setView(name)}>{name}<b>{count}</b></button>{viewLogic[name] && <LogicTooltip title={name} {...viewLogic[name]} />}</span>)}</div>
      <div className="table-controls"><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order, customer, reference or warehouse" /></label><button className="filter" onClick={() => setFiltersOpen((current) => !current)}>Filters <span>2</span></button><button className="filter" onClick={() => setColumnsOpen((current) => !current)}>Columns</button><button className="filter">Export</button></div>
      {filtersOpen && <div className="filter-drawer"><b>Active filters</b><span>Client: All clients</span><span>Warehouse: All warehouses</span><span>SLA: At risk or breached</span><button onClick={() => setFiltersOpen(false)}>Done</button></div>}
      {columnsOpen && <div className="columns-drawer"><b>Optional columns</b>{optionalFields.map((field) => <label key={field}><input type="checkbox" checked={visibleOptional.includes(field)} onChange={() => toggleColumn(field)} /> {field}</label>)}<button onClick={() => setColumnsOpen(false)}>Done</button></div>}
      {view === "Action Required" ? <ActionRequiredTable /> : <DenseTable rows={filtered} showClient={!clientScoped} optional={visibleOptional} />}
    </section>{createMode === "single" && <SingleOrderPanel close={() => setCreateMode(null)} />}{createMode === "bulk" && <BulkUploadPanel close={() => setCreateMode(null)} />}
  </>;
}

function SummaryCard({ label, value, detail, warn = false }: { label: string; value: string; detail: string; warn?: boolean }) { const explanation = summaryLogic[label]; return <article><span>{explanation ? <LogicLabel title={label} {...explanation}>{label}</LogicLabel> : label}</span><b>{value}</b><small className={warn ? "red-text" : ""}>{detail}</small></article> }

function SingleOrderPanel({ close }: { close: () => void }) { return <div className="modal-backdrop"><section className="create-panel single-order-panel" role="dialog" aria-modal="true"><button className="drawer-close" onClick={close}>×</button><h2>Create single order</h2><p>Manual orders enter the same standard Validating state and follow the same validation, routing and fulfilment lifecycle as storefront and API orders.</p><div className="single-order-fields">{["External order reference", "Client", "Customer", "Delivery address", "SKU & quantity"].map((field) => <label key={field}>{field}<input placeholder={field} /></label>)}</div><button className="primary">Create validating order</button></section></div> }

function BulkUploadPanel({ close }: { close: () => void }) { const [step, setStep] = useState(1); const bulkSteps: Array<[number, string]> = [[1,"Upload"],[2,"Validate"],[3,"Review"],[4,"Create valid orders"]]; return <div className="modal-backdrop"><section className="create-panel bulk-upload-panel" role="dialog" aria-modal="true"><button className="drawer-close" onClick={close}>×</button><div className="bulk-head"><div><h2>Bulk upload orders</h2><p>Each row is validated independently before it enters the standard Bundle order lifecycle.</p></div><button className="text-button">Download template ↓</button></div><div className="bulk-steps">{bulkSteps.map(([number,label]) => <button className={step === number ? "active" : step > number ? "complete" : ""} onClick={() => setStep(number)} key={label}><i>{step > number ? "✓" : number}</i>{label}</button>)}</div>{step === 1 && <div className="upload-step"><div className="upload-drop"><b>⇧</b><h3>Upload CSV or XLSX</h3><p>Preserve the client&apos;s external order reference in every row.</p><button className="outline" onClick={() => setStep(2)}>Select file</button></div><small>Template columns: External order reference, customer, address, SKU, quantity, service and dispatch date.</small></div>}{step === 2 && <div className="validation-step"><h3>263 rows uploaded</h3><p>Bundle is validating every row against the same schema, inventory, routing and state rules used for API and storefront orders.</p><button className="primary" onClick={() => setStep(3)}>View validation results</button></div>}{step >= 3 && <div className="review-step"><div className="validation-counts"><div><b>247</b><span>Valid</span></div><div><b className="amber-text">12</b><span>Warnings</span></div><div><b className="red-text">4</b><span>Invalid</span></div></div><p>Invalid rows never block valid rows. Created orders enter <b>Validating</b> and follow exactly the same validation, routing and state machine as API/storefront orders.</p><div className="invalid-rows"><b>Invalid rows</b><div><span>Row 18 · Postcode</span><small>Postcode does not match destination country.</small></div><div><span>Row 74 · SKU</span><small>SKU SHOW-TRVL-4 is not mapped to London Fulfilment.</small></div><div><span>Row 121 · Quantity</span><small>Quantity must be a positive integer.</small></div><div><span>Row 202 · External reference</span><small>Duplicate external order reference for this client.</small></div></div><div className="bulk-actions"><button className="outline" onClick={() => setStep(3)}>Review 4 invalid rows</button><button className="primary">Create 247 valid orders</button></div></div>}</section></div> }

function DenseTable({ rows, showClient, optional }: { rows: Order[]; showClient: boolean; optional: OptionalField[] }) { const value = (order: Order, field: OptionalField) => ({ "Integration State": order.integration, Country: order.country, Courier: order.courier, Source: order.source, Created: order.created, "Required Despatch": order.despatch })[field]; const heading = (label: string) => tableLogic[label] ? <LogicLabel title={label} {...tableLogic[label]}>{label}</LogicLabel> : label; return <div className="orders-table-wrap dense-table"><div className="table-meta">{rows.length} matching orders <span>•</span> Updated just now</div><table className="orders-table"><thead><tr><th>Order</th>{showClient && <th>Client</th>}<th>Order Type</th><th>{heading("Order State")}</th><th>{heading("WMS State")}</th><th>{heading("Shipment State")}</th><th>{heading("SLA")}</th><th>Warehouse</th><th>{heading("Exception")}</th><th>{heading("Owner")}</th><th>Updated</th>{optional.map((field) => <th key={field}>{field}</th>)}</tr></thead><tbody>{rows.map((order) => <tr key={order.id} className="order-row"><td><Link href={`/orders/${order.id}`}><b>#{order.id}</b></Link></td>{showClient && <td>{order.client}</td>}<td>{order.type}</td><td>{badge(order.state)}</td><td>{order.wms}</td><td>{order.shipment}</td><td>{badge(order.sla)}</td><td>{order.warehouse}</td><td>{order.exception === "—" ? <span className="quiet">—</span> : <Link className="order-issue" href={`/orders/${order.id}`}>{order.exception}</Link>}</td><td>{order.owner}</td><td>{order.updated}</td>{optional.map((field) => <td key={field}>{value(order, field)}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state">No orders match the selected saved view and search.</div>}</div> }

const actionRequired = [
  { id: "BW-10471", client: "Canyon Club", severity: "Critical", type: "WMS push failed", reason: "The warehouse rejected the order because its SKU is not enabled.", owner: "Tech", assignee: "Maya Patel", age: "28m", sla: "At Risk", action: "Correct the SKU mapping, then retry WMS push." },
  { id: "BW-10480", client: "Aster & Ash", severity: "High", type: "Delivery address needs correcting", reason: "The postcode does not match the destination country.", owner: "Client", assignee: "—", age: "12m", sla: "Breached", action: "Correct the delivery postcode in Shopify." },
  { id: "BW-10477", client: "Aster & Ash", severity: "High", type: "Quantity mismatch", reason: "One unit is outstanding after shipment reconciliation.", owner: "Warehouse", assignee: "Jess Lin", age: "22m", sla: "At Risk", action: "Confirm the residual fulfilment plan." },
  { id: "BW-10463", client: "Kanso Studio", severity: "Medium", type: "Cancellation awaiting confirmation", reason: "The warehouse has not yet confirmed the cancellation request.", owner: "Warehouse", assignee: "—", age: "41m", sla: "At Risk", action: "Contact the warehouse before pick lock." },
  { id: "BW-10458", client: "Aster & Ash", severity: "Medium", type: "Stalled WMS event", reason: "No expected warehouse event has arrived within the configured threshold.", owner: "Tech", assignee: "Maya Patel", age: "1h", sla: "Within SLA", action: "Inspect the integration event trace." },
];

function ActionRequiredTable() { return <div className="orders-table-wrap dense-table action-required-table"><div className="table-meta">18 action-required orders <span>•</span> Prioritised by severity, SLA impact and exception age</div><table className="orders-table"><thead><tr><th>Severity</th><th>Order</th><th>Client</th><th>Exception type</th><th>Plain-language reason</th><th>Owner</th><th>Assignee</th><th>Age</th><th>SLA</th><th>Recommended next action</th></tr></thead><tbody>{actionRequired.map((item) => <tr key={item.id}><td><span className={`severity-label ${item.severity.toLowerCase()}`}>{item.severity}</span></td><td><Link href={`/orders/${item.id}`}><b>#{item.id}</b></Link></td><td>{item.client}</td><td><Link className="order-issue" href={`/orders/${item.id}`}>{item.type}</Link></td><td className="exception-reason">{item.reason}</td><td><b>{item.owner}</b></td><td>{item.assignee}</td><td>{item.age}</td><td>{badge(item.sla)}</td><td className="recommended-action">{item.action}</td></tr>)}</tbody></table></div> }
